create database MOTO_CRAFT;

use MOTO_CRAFT;
CREATE TABLE MOTO_CRAFT.PRODUTO (
ID INT AUTO_INCREMENT,
NOME VARCHAR (100),
DESCRICAO VARCHAR (100),
PRECO VARCHAR (20),
PRIMARY KEY (ID)
);

INSERT INTO MOTO_CRAFT.PRODUTO (NOME, DESCRICAO, PRECO)
VALUES ('Capacete Norisk FF391', 'PRODUTO DESCRICAO', '399.00');

INSERT INTO MOTO_CRAFT.PRODUTO (NOME, DESCRICAO, PRECO)
VALUES ('Capacete Axxis Joker', 'PRODUTO DESCRICAO', '354.90');

INSERT INTO MOTO_CRAFT.PRODUTO (NOME, DESCRICAO, PRECO)
VALUES ('Capacete LS2 Alex Barros', 'PRODUTO DESCRICAO', '699.00');

INSERT INTO MOTO_CRAFT.PRODUTO (NOME, DESCRICAO, PRECO)
VALUES ('Capacete Norisk FF391', 'PRODUTO DESCRICAO', '399.00');

INSERT INTO MOTO_CRAFT.PRODUTO (NOME, DESCRICAO, PRECO)
VALUES ('Luva X11', 'PRODUTO DESCRICAO', '59.90');

INSERT INTO MOTO_CRAFT.PRODUTO (NOME, DESCRICAO, PRECO)
VALUES ('Capa de Chuva Arizona', 'PRODUTO DESCRICAO', '199.00');

